name: transformo-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - click=8.1
  - numpy=2.0
  - pyproj=3.7
  - pydantic=2.8
  - pydantic-yaml=1.3
  - pandoc=3.5
  - rich=13.9
  - pytest
  - black
  - pylint
  - pre-commit
  - mypy
  - isort
  - pip:
    - pandoc
    - py-markdown-table=1.2
