name: transformo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip=25
  - numpy=2.0
  - pydantic=2.8
  - pydantic-yaml=1.3
  - pyproj=3.7
  - pandoc=3.5
  - rich=13.9
  - pip:
    - pandoc
    - py-markdown-table
