name: Tests
'on': [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
          miniforge-version: latest
          use-mamba: true
          environment-file: environment-dev.yml
          auto-activate-base: false
          activate-environment: transformo-dev
    - run: |
        conda info
        conda list

    - name: Install Transformo
      run: |
        pip install -e .

    - name: Run test-suite
      run: pytest
